import {
  BadRequestException,
  NotFoundException,
  Inject,
  Injectable,
} from '@nestjs/common';
import { BackupProfileRepositoryPort } from '../../ports/backupProfile.repository';

@Injectable()
export class SaveBackupProfileUseCase {
  constructor(
    @Inject('BackupProfileRepository')
    private readonly backupProfileRepository: BackupProfileRepositoryPort,
  ) {}

  async handler(data: any, uid?: string): Promise<any> {
    if (uid) {
      // Update existing profile by UID
      return await this.updateBackupProfile(data, uid);
    } else {
      // Create new profile
      return await this.createBackupProfile(data);
    }
  }

  private async createBackupProfile(data: any): Promise<any> {
    // Business validation
    if (!data.poiId || !data.poiLayerId) {
      throw new BadRequestException('POI ID and POI Layer ID are required');
    }

    if (!data.strategicLocation) {
      throw new BadRequestException('Strategic Location is required');
    }

    // Check if backup profile already exists for this POI ID
    const existingProfile = await this.backupProfileRepository.findByPoiId(data.poiId);
    if (existingProfile) {
      throw new BadRequestException('มี Backup Profile ของ POI นี้แล้ว');
    }

    // Set default values (uid will be generated by database)
    const profileData = {
      ...data,
      isActive: data.isActive || 'Y',
      createDate: new Date(),
    };

    // Create backup profile with related records
    return await this.backupProfileRepository.createBackupProfile(profileData);
  }

  private async updateBackupProfile(data: any, uid: string): Promise<any> {
    // Business validation
    if (!uid) {
      throw new BadRequestException('UID is required');
    }

    // Check if backup profile exists by UID from parameter
    // const existingProfile = await this.backupProfileRepository.findByUid(uid);
    // if (!existingProfile) {
    //   throw new NotFoundException('ไม่พบ Backup Profile');
    // }

    // Set update metadata
    const profileData = {
      ...data,
      updateDate: new Date(),
    };

    // Update backup profile with related records using found id
    return await this.backupProfileRepository.updateBackupProfile(uid, profileData);
  }
}
